version: "3.7"

services:
  playground:
    container_name: mbti-playground
    build:
      context: .
      dockerfile: ./apps/playground/Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
